name: quality-check
on: [ pull_request ]

jobs:
  checkstyle:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: './src/main/resources/checkstyle.xml'
          workdir: './src/main/java'
          reporter: 'github-pr-check'
          tool_name: 'checkstyle'

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        java: [ '17' ]
        db: [ 'postgres:15' ]
        rabbitmq: [ 'rabbitmq:management' ]
    runs-on: ${{ matrix.os }}
    services:
      rabbitmq:
        image: ${{ matrix.rabbitmq }}
        env:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin
        ports:
          - 5672:5672
        options: --health-cmd="rabbitmq-diagnostics -q ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: ${{ matrix.db }}
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U root" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java ${{ matrix.Java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Set up postgres
        run: |
          PGPASSWORD=root psql -h 127.0.0.1 -p 5432 -U root -c "CREATE USER race_user WITH PASSWORD 'race_password'"
          PGPASSWORD=root psql -h 127.0.0.1 -p 5432 -U root -c "CREATE DATABASE race_db WITH ENCODING 'UTF8' LC_COLLATE 'C.UTF-8' LC_CTYPE 'C.UTF-8' TEMPLATE template0;"
          PGPASSWORD=root psql -h 127.0.0.1 -p 5432 -U root -c "GRANT ALL PRIVILEGES ON DATABASE race_db TO race_user;"

      - name: Build with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
        run: |
          mvn -Dmaven.javadoc.skip=true verify \
          -DdatasourceUrl="jdbc:postgresql://localhost:5432/race_db?sslMode=disable&allowPublicKeyRetrieval=true" \
          -DdatasourceUsername=race_user \
          -DdatasourcePassword=race_password \
          -DdatasourceName=race_db \
          --no-transfer-progress
